version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@8.2.1 

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.0.5-node'
    steps:
      - checkout
      - setup_remote_docker
      - ruby/install-deps
      - run:
          name: test build site
          command: bash build.sh
  test:
    docker:
      - image: 'cimg/ruby:3.0.5-node'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: test build site
          command: bash build.sh
      - run:
          name: test build site - htmlproofer
          command: |
            htmlproofer ./build --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
  build_and_push_staging:
    docker:
      - image: 'cimg/ruby:3.0.5-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME_STAGING
          region: $ECR_REGION_STAGING
      - setup_remote_docker:
          docker_layer_caching: true
      - ruby/install-deps
      - run:
          name: Build and Push
          command: bash scripts/build_and_push.sh
  build_and_push_prod:
    docker:
      - image: 'cimg/ruby:3.0.5-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME_STAGING
          region: $ECR_REGION_STAGING
      - setup_remote_docker:
          docker_layer_caching: true
      - ruby/install-deps
      - run:
          name: Build and Push
          command: bash scripts/build_and_push.sh


workflows:
  version: 2
  build_and_test:
    jobs:
     - build
     - build_and_push_staging:
        requires:
          - build
        filters:
          branches:
            ignore:
              - master
              - main
     - build_and_push_prod:
        requires:
          - build
        filters:
            branches:
              only:
                - master
                - main



