version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@8.2.1 

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.2.2-node'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: build site
          command: bash build.sh
      - persist_to_workspace:
          root: .
          paths:
            - build
  lint:
    docker:
      - image: 'cimg/ruby:3.2.2-node'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: test build site
          command: bash build.sh
      - run:
          name: htmlproofer checks
          command: .gem-bin/htmlproofer ./build
  build_and_push_staging:
    docker:
      - image: 'cimg/base:current'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME_STAGING
          region: $ECR_REGION_STAGING
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name: Build and Push
          command: bash scripts/build_and_push.sh
  build_and_push_prod:
    docker:
      - image: 'cimg/base:current'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME_PROD
          region: $ECR_REGION_PROD
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name: Build and Push
          command: bash scripts/build_and_push.sh


workflows:
  version: 2
  build_and_test:
    jobs:
     - build
     - lint:
         requires:
           - build
     - build_and_push_staging:
        requires:
          - lint
     - build_and_push_prod:
        requires:
          - build_and_push_staging
        filters:
          branches:
            only:
              - main
