version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7.5-node'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: test build site
          command: bash build.sh
  test:
    docker:
      - image: 'cimg/ruby:2.7.5-node'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: test build site
          command: bash build.sh
      - run:
          name: test build site - htmlproofer
          command: |
            htmlproofer ./build --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
  build_and_push_staging:
    docker:
      - image: 'cimg/ruby:2.7.5-node'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Build and Push
          command: ./scripts/build_and_push.sh


workflows:
  version: 2
  build_and_deploy_staging:
    jobs:
      - build_and_push_staging







