name: Deploy to Staging in EKS Cluster
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build and push staging
      env:
        ENVIRONMENT: staging
        EKS_TOKEN: ${{ secrets.FB_PRODUCT_PAGE_EKS_TOKEN_STAGING }}
        EKS_CLUSTER_CERT: ${{ secrets.FB_PRODUCT_PAGE_EKS_CERT_STAGING}}
        EKS_CLUSTER_NAME: ${{ secrets.FB_PRODUCT_PAGE_EKS_CLUSTER }}
        SERVICE_ACCOUNT: ${{ secrets.FB_PRODUCT_PAGE_SERVICE_ACCOUNT_STAGING }}
        EKS_NAMESPACE: formbuilder-product-page-staging
        ECR_CREDENTIALS_SECRET: formbuilder-product-page-staging-ecr-credentials-output
        ECR_USERNAME: ${{ secrets.FB_PRODUCT_PAGE_ECR_USERNAME }}
        ECR_PASSWORD: ${{ secrets.FB_PRODUCT_PAGE_ECR_PASSWORD }}
        BASIC_AUTH_STAGING: ${{ secrets.FB_BASIC_AUTH_STAGING }}
      run: ./scripts/build_and_push_eks.sh
